# Generated by Django 5.2.5 on 2025-08-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "permissions": [
                    ("block_user", "Can block users"),
                    ("view_all_clients", "Can view all clients"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [("disable_newsletter", "Can disable newsletters")]
            },
        ),
        migrations.AddField(
            model_name="newsletter",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
