# Generated by Django 5.2.5 on 2025-08-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_client_alter_newsletter_options_newsletter_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
    ]
